In [31]:
import numpy as np

a = np.array([10,20,30,40])
print (a)

b = np.arange( 1,11 )
print (b)

c = np.linspace (1,10,5)
print (c)


d = np.random.randint(1,20, size = (3,3))
print ("Matrix A :\n",d, "\n")

e =  np.random.randint(1,20 , size = (3,3))
print ("Matrix B :\n" ,e, "\n\n")

print ( "Sum :\n", d + e , "\n")
print ("Difference :\n ", d - e , "\n")
print ("Product : \n", d * e, "\n")

# Used to multiply elements with each other
print ("Element Multiplication :\n" ,d @ e, "\n")


f = np.array([10,30,50,25,22,68])
print (np.mean(f))
print ("\n", np.max(f), "\n")
print ("\n" , np.min(f), "\n")
print ("\n" , np.std(f), "\n")

print ("Weather Data of Udupi of July")

weather_data = np.array([
    [1, 25],  [2, 25],  [3, 26],  [4, 26],  [5, 27],
    [6, 27],  [7, 26],  [8, 26],  [9, 26],  [10, 26],
    [11, 27], [12, 27], [13, 28], [14, 28], [15, 28],
    [16, 26], [17, 25], [18, 26], [19, 25], [20, 25],
    [21, 26], [22, 25], [23, 25], [24, 35], [25, 25],
    [26, 26], [27, 25], [28, 26], [29, 35], [30, 26],
    [31, 24]
], dtype=float)

temp = weather_data[:,1]
print (" Hottest Day is  " ,np.max(temp) , "\n" )
print (" Coldest Day is  " ,np.min(temp) , "\n" )
print (" Average Temp is  " ,np.average(temp) , "\n" )

days = weather_data[:,0]
date_35 = days[temp>=35]
print ("\n Days with temp greater than 35 : ", date_35)


[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]
Matrix A :
 [[ 2  9  9]
 [18  2  5]
 [ 1 11  8]] 

Matrix B :
 [[ 3  6 17]
 [10  3 16]
 [15 14 12]] 


Sum :
 [[ 5 15 26]
 [28  5 21]
 [16 25 20]] 

Difference :
  [[ -1   3  -8]
 [  8  -1 -11]
 [-14  -3  -4]] 

Product : 
 [[  6  54 153]
 [180   6  80]
 [ 15 154  96]] 

Element Multiplication :
 [[231 165 286]
 [149 184 398]
 [233 151 289]] 

34.166666666666664

 68 


 10 


 19.273614664152184 

Weather Data of Udupi of July
 Hottest Day is   35.0 

 Coldest Day is   24.0 

 Average Temp is   26.548387096774192 


 Days with temp greater than 35 :  [24. 29.]


In [48]:
!git config --global user.email "dhanush.erramuri.raj@gmail.com"
!git config --global user.name "dhanusherramuri"
!git remote add origin https://github.com/dhanusherramuri/AML_MSIS.git

fatal: not a git repository (or any parent up to mount point /content)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


In [56]:
!git push -u origin main

error: src refspec main does not match any
error: failed to push some refs to 'origin'
