In [67]:
import numpy as np

a = np.array([10,20,30,40])
print (a)

b = np.arange( 1,11 )
print (b)

c = np.linspace (1,10,5)
print (c)


d = np.random.randint(1,20, size = (3,3))
print ("Matrix A :\n",d, "\n")

e =  np.random.randint(1,20 , size = (3,3))
print ("Matrix B :\n" ,e, "\n\n")

print ( "Sum :\n", d + e , "\n")
print ("Difference :\n ", d - e , "\n")
print ("Product : \n", d * e, "\n")

# Used to multiply elements with each other
print ("Element Multiplication :\n" ,d @ e, "\n")


f = np.array([10,30,50,25,22,68])
print (np.mean(f))
print ("\n", np.max(f), "\n")
print ("\n" , np.min(f), "\n")
print ("\n" , np.std(f), "\n")

print ("Weather Data of Udupi of July")

weather_data = np.array([
    [1, 25],  [2, 25],  [3, 26],  [4, 26],  [5, 27],
    [6, 27],  [7, 26],  [8, 26],  [9, 26],  [10, 26],
    [11, 27], [12, 27], [13, 28], [14, 28], [15, 28],
    [16, 26], [17, 25], [18, 26], [19, 25], [20, 25],
    [21, 26], [22, 25], [23, 25], [24, 35], [25, 25],
    [26, 26], [27, 25], [28, 26], [29, 35], [30, 26],
    [31, 24]
], dtype=float)

temp = weather_data[:,1]
print (" Hottest Day is  " ,np.max(temp) , "\n" )
print (" Coldest Day is  " ,np.min(temp) , "\n" )
print (" Average Temp is  " ,np.average(temp) , "\n" )

days = weather_data[:,0]
date_35 = days[temp>=35]
print ("\n Days with temp greater than 35 : ", date_35)


[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]
Matrix A :
 [[ 5  1 15]
 [16 18  6]
 [ 6 13 10]] 

Matrix B :
 [[16  6 17]
 [ 6  6 18]
 [ 2 10 10]] 


Sum :
 [[21  7 32]
 [22 24 24]
 [ 8 23 20]] 

Difference :
  [[-11  -5  -2]
 [ 10  12 -12]
 [  4   3   0]] 

Product : 
 [[ 80   6 255]
 [ 96 108 108]
 [ 12 130 100]] 

Element Multiplication :
 [[116 186 253]
 [376 264 656]
 [194 214 436]] 

34.166666666666664

 68 


 10 


 19.273614664152184 

Weather Data of Udupi of July
 Hottest Day is   35.0 

 Coldest Day is   24.0 

 Average Temp is   26.548387096774192 


 Days with temp greater than 35 :  [24. 29.]


In [79]:
from sklearn import datasets

iris = datasets.load_iris(as_frame = True)

# iris = load_iris (as_frame = True)
df = iris.frame

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [82]:
!git status
!git remote -v

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   AML_LAB_1(04-08-2026).ipynb

no changes added to commit (use "git add" and/or "git commit -a")
origin	https://github.com/dhanusherramuri/AML_MSIS.git (fetch)
origin	https://github.com/dhanusherramuri/AML_MSIS.git (push)
